### ISSUE TITLE
segfault in lrec_reader_mmap_csv_get_fields at lrec_reader_mmap_csv.c:317

### ISSUE THREAD

**Issue by geeknik** [johnkerl/miller#102]
While fuzzing miller with American Fuzzy Lop, I encountered a segfault in lrec_reader_mmap_csv_get_fields at lrec_reader_mmap_csv.c:317.

/home/geeknik/miller/c/mlr --icsv --oxtab cat test00.csv where test00.csv contains """ as seen here:
```
hexdump -C test00.csv
00000000  22 22 22      |"""|
00000003
```

```
#0  lrec_reader_mmap_csv_get_fields (pstate=pstate@entry=0x7ab2b0, pfields=<optimized out>, 
    phandle=0x7b1510, phandle=0x7b1510) at lrec_reader_mmap_csv.c:317
#1  0x0000000000501cb7 in lrec_reader_mmap_csv_process (pvstate=0x7ab2b0, pvhandle=0x7b1510, 
    pctx=0x7fffffffe160) at lrec_reader_mmap_csv.c:154
#2  0x000000000055f61f in do_file_chained (prepipe=0x0, filename=<optimized out>, pctx=0x7fffffffe160, 
    plrec_reader=0x7ab270, plrec_writer=0x7ab0a0, output_stream=0x7ffff7ad62a0 <_IO_2_1_stdout_>, 
    nr_progress_mod=0, pmapper_list=<optimized out>) at stream.c:79
#3  0x000000000055fae2 in do_stream_chained (prepipe=0x7adc90 "", filenames=0x7b1518, 
    plrec_reader=0x7c0d80, pmapper_list=0x7ab0f0, plrec_writer=0x7ab0a0, 
    ofmt=0x9ffe <error: Cannot access memory at address 0x9ffe>, nr_progress_mod=0) at stream.c:52
#4  0x0000000000402a13 in main (argc=<optimized out>, argv=0x7fffffffe2e8) at mlrmain.c:27
(gdb) list
312							break;
313						}
314						e += matchlen;
315					} else {
316						if (!contiguous)
317							sb_append_char(psb, *e);
318						e++;
319					}
320				}
321			}
```

**Comment by johnkerl** [comment]
looking. and, thank you!!
