### ISSUE TITLE
segfault on joining files with comments and unexpected behavior when joining more than 2 files

### ISSUE THREAD

**Issue by BEFH** [johnkerl/miller#1037]
When I run the join verb on files with header comments, it segfaults like so:

with two files

```
# something
foo	bar	a	b	c
1	a	1	2	3
2	b	3	2	1
```

and

```
# something
foo	bar	d	e	f
1	a	4	5	6
2	b	6	5	4
```

The following happens:

```
$ mlr --tsv --pass-comments join -j 'foo,bar' -f ex1_com.tsv ex2_com.tsv
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x670fa3]

goroutine 21 [running]:
github.com/johnkerl/miller/internal/pkg/mlrval.(*Mlrmap).findEntry(...)
        /home/conda/feedstock_root/build_artifacts/miller_1647792828362/work/internal/pkg/mlrval/mlrmap_accessors.go:196
github.com/johnkerl/miller/internal/pkg/mlrval.(*Mlrmap).GetSelectedValuesAndJoined(0x0, {0xc0000d6840, 0x2, 0x0})
        /home/conda/feedstock_root/build_artifacts/miller_1647792828362/work/internal/pkg/mlrval/mlrmap_accessors.go:591 +0x103
github.com/johnkerl/miller/internal/pkg/transformers.(*TransformerJoin).ingestLeftFile(0xc0000d83c0)
        /home/conda/feedstock_root/build_artifacts/miller_1647792828362/work/internal/pkg/transformers/join.go:531 +0x578
github.com/johnkerl/miller/internal/pkg/transformers.(*TransformerJoin).transformHalfStreaming(0xc0000d83c0, 0xc00007c140, 0xc000200000, 0x28, 0xc000150070)
        /home/conda/feedstock_root/build_artifacts/miller_1647792828362/work/internal/pkg/transformers/join.go:387 +0x32
github.com/johnkerl/miller/internal/pkg/transformers.(*TransformerJoin).Transform(0xc0000d83c0, 0xc0000bab40, 0x0, 0x0, 0x0)
        /home/conda/feedstock_root/build_artifacts/miller_1647792828362/work/internal/pkg/transformers/join.go:368 +0x5d
github.com/johnkerl/miller/internal/pkg/transformers.runSingleTransformerBatch(0xc00007e060, {0x90d760, 0xc0000d83c0}, 0x1, 0x0, 0x0, 0x0, 0xc000083860)
        /home/conda/feedstock_root/build_artifacts/miller_1647792828362/work/internal/pkg/transformers/aaa_chain_transformer.go:269 +0x2ce
github.com/johnkerl/miller/internal/pkg/transformers.runSingleTransformer({0x90d760, 0xc0000d83c0}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/conda/feedstock_root/build_artifacts/miller_1647792828362/work/internal/pkg/transformers/aaa_chain_transformer.go:212 +0x92
created by github.com/johnkerl/miller/internal/pkg/transformers.ChainTransformer
        /home/conda/feedstock_root/build_artifacts/miller_1647792828362/work/internal/pkg/transformers/aaa_chain_transformer.go:187 +0x2ef
```

This does not occur with the same command if the comment is removed in the input files.

I also identified an issue with multiple input files being concatenated instead of joined.

With a third file like this:

```
foo	bar	g	h	i
1	a	7	8	9
2	b	9	8	7
```

The output is

```
$ mlr --tsv --pass-comments join -j 'foo,bar' -f ex1.tsv ex2.tsv ex3.tsv
foo     bar     a       b       c       d       e       f
1       a       1       2       3       4       5       6
2       b       3       2       1       6       5       4

foo     bar     a       b       c       g       h       i
1       a       1       2       3       7       8       9
2       b       3       2       1       9       8       7
```

I can actually work around the segfault issue by removing comments, but the multi-file merge is problematic.

**Comment by aborruso** [comment]
Hi @BEFH do you want also to join the two lines of comment, and to merge it in some way in the join output?

If no, you can run

```
mlr --tsv --skip-comments join -j 'foo,bar' -f ex1.tsv ex2.tsv ex3.tsv
```

**Comment by aborruso** [comment]
> I also identified an issue with multiple input files being concatenated instead of joined.

There is a FAQ about it https://miller.readthedocs.io/en/latest/questions-about-joins/#doing-multiple-joins

Running

```
mlr --tsv --skip-comments join -f ex1.tsv -j 'foo,bar' -f 01.tsv then join -f ex2.tsv -j 'foo,bar' ex3.tsv
```

you will have

```
foo     bar     d       e       f       a       b       c       g       h       i
1       a       4       5       6       1       2       3       7       8       9
2       b       6       5       4       3       2       1       9       8       7
```

**Comment by BEFH** [comment]
My workaround for an arbitrary number of files is this. It's ugly but works.

```bash
tsvs=(ex1.tsv ex2.tsv ex3.tsv ex4.tsv ex5.tsv ex6.tsv) # make array of inputs
cp "${tsvs[0]}" ex_merged.tsv # copy first input to output
tsvs=("${tsvs[@]:1}") # delete first input from array

for tsv in ${tsvs[@]}; do
  mlr --tsv join -j 'foo,bar' -f ex_merged.tsv \
    $tsv > ex_merged.tsv
done
```

**Comment by BEFH** [comment]
> Hi @BEFH do you want also to join the two lines of comment, and to merge it in some way in the join output?
> 
> If no, you can run
> 
> ```
> mlr --tsv --skip-comments join -j 'foo,bar' -f ex1_com.tsv ex2_com.tsv
> ```

So it appears that only keeping the comments will cause the segfault. This is good.

**Comment by johnkerl** [comment]
Hi @BEFH and @aborruso -- apologies on my delay in responding to this (and to everything else Miller-related) -- the last few months I've self-saturated at work on https://github.com/single-cell-data/TileDB-SingleCell/tree/main/apis/python.

#1047 resolves this -- please let me know if I missed anything & we need to re-open -- thank you!
