### ISSUE TITLE
Is sort just broken?

### ISSUE THREAD

**Issue by indigoviolet** [johnkerl/miller#1072]
I'm missing something basic -- but `mlr sort` simply won't return any results:

```
❯ mlr --csv head ../wikidata/P1056.csv    
subject,subjectLabel,object,objectLabel
http://www.wikidata.org/entity/Q524931,coup de grâce,http://www.wikidata.org/entity/Q4,death
http://www.wikidata.org/entity/Q6437079,Krinos Foods,http://www.wikidata.org/entity/Q41,Greece
http://www.wikidata.org/entity/Q7050424,Norbest,http://www.wikidata.org/entity/Q43,Turkey
http://www.wikidata.org/entity/Q4990,Ursus Breweries,http://www.wikidata.org/entity/Q44,beer
http://www.wikidata.org/entity/Q4995,SABMiller,http://www.wikidata.org/entity/Q44,beer
http://www.wikidata.org/entity/Q106854,Beck's,http://www.wikidata.org/entity/Q44,beer
http://www.wikidata.org/entity/Q113215,Carlsberg Group,http://www.wikidata.org/entity/Q44,beer
http://www.wikidata.org/entity/Q127305,Paulaner Brewery,http://www.wikidata.org/entity/Q44,beer
http://www.wikidata.org/entity/Q129645,Sabeco,http://www.wikidata.org/entity/Q44,beer
http://www.wikidata.org/entity/Q131734,brewery,http://www.wikidata.org/entity/Q44,beer

❯ mlr --csv sort -f subject,object ../wikidata/P1056.csv
Usage: mlr sort {flags}
Sorts records primarily by the first specified field, secondarily by the second
field, and so on.  (Any records not having all specified sort keys will appear
at the end of the output, in the order they were encountered, regardless of the
specified sort order.) The sort is stable: records that compare equal will sort
in the order they were encountered in the input record stream.

Options:
-f  {comma-separated field names}  Lexical ascending
-r  {comma-separated field names}  Lexical descending
-c  {comma-separated field names}  Case-folded lexical ascending
-cr {comma-separated field names}  Case-folded lexical descending
-n  {comma-separated field names}  Numerical ascending; nulls sort last
-nf {comma-separated field names}  Same as -n
-nr {comma-separated field names}  Numerical descending; nulls sort first
-t  {comma-separated field names}  Natural ascending
-tr {comma-separated field names}  Natural descending
-h|--help Show this message.

Example:
  mlr sort -f a,b -nr x,y,z
which is the same as:
  mlr sort -f a -f b -nr x -nr y -nr z

❯ mlr --version               
mlr 6.3.0
```

**Comment by aborruso** [comment]
> I'm missing something basic -- but `mlr sort` simply won't return any results:

If I run it, it works (but I have `mlr 6.2.0-dev`), and I have

| subject | subjectLabel | object | objectLabel |
| --- | --- | --- | --- |
| http://www.wikidata.org/entity/Q106854 | Beck's | http://www.wikidata.org/entity/Q44 | beer |
| http://www.wikidata.org/entity/Q113215 | Carlsberg Group | http://www.wikidata.org/entity/Q44 | beer |
| http://www.wikidata.org/entity/Q127305 | Paulaner Brewery | http://www.wikidata.org/entity/Q44 | beer |
| http://www.wikidata.org/entity/Q129645 | Sabeco | http://www.wikidata.org/entity/Q44 | beer |
| http://www.wikidata.org/entity/Q131734 | brewery | http://www.wikidata.org/entity/Q44 | beer |
| http://www.wikidata.org/entity/Q4990 | Ursus Breweries | http://www.wikidata.org/entity/Q44 | beer |
| http://www.wikidata.org/entity/Q4995 | SABMiller | http://www.wikidata.org/entity/Q44 | beer |
| http://www.wikidata.org/entity/Q524931 | coup de grâce | http://www.wikidata.org/entity/Q4 | death |
| http://www.wikidata.org/entity/Q6437079 | Krinos Foods | http://www.wikidata.org/entity/Q41 | Greece |
| http://www.wikidata.org/entity/Q7050424 | Norbest | http://www.wikidata.org/entity/Q43 | Turkey |

**Comment by indigoviolet** [comment]
It continues to not work for me :) What debugging information can I provide?

**Comment by aborruso** [comment]
> It continues to not work for me :) What debugging information can I provide?

What do you have if you copy, paste and run this

```
mlrgo --csv sort -f subject,object "https://gist.githubusercontent.com/aborruso/9aa2521cd92b2c6cff9f52e4deb54444/raw/2be80887ec2289d3c7804b89359d5c3025cadf6e/input_01.csv"
```

**Comment by aborruso** [comment]
I misspelled the command, I corrected it

**Comment by indigoviolet** [comment]
The same:

```
❯ mlr --csv sort -f subject,object "https://gist.githubusercontent.com/aborruso/9aa2521cd92b2c6cff9f52e4deb54444/raw/2be80887ec2289d3c7804b89359d5c3025cadf6e/input_01.csv"
Usage: mlr sort {flags}
Sorts records primarily by the first specified field, secondarily by the second
field, and so on.  (Any records not having all specified sort keys will appear
at the end of the output, in the order they were encountered, regardless of the
specified sort order.) The sort is stable: records that compare equal will sort
in the order they were encountered in the input record stream.

Options:
-f  {comma-separated field names}  Lexical ascending
-r  {comma-separated field names}  Lexical descending
-c  {comma-separated field names}  Case-folded lexical ascending
-cr {comma-separated field names}  Case-folded lexical descending
-n  {comma-separated field names}  Numerical ascending; nulls sort last
-nf {comma-separated field names}  Same as -n
-nr {comma-separated field names}  Numerical descending; nulls sort first
-t  {comma-separated field names}  Natural ascending
-tr {comma-separated field names}  Natural descending
-h|--help Show this message.

Example:
  mlr sort -f a,b -nr x,y,z
which is the same as:
  mlr sort -f a -f b -nr x -nr y -nr z
```

**Comment by johnkerl** [comment]
@indigoviolet this is very strange 🤔 ...

A few thoughts:

* What does `which mlr` show?
* What does `ls -l $(which mlr)` show?
* What does `echo 'mlr --csv sort -f subject ... | od -a` show?
* What does `alias mlr` show?
* What if you replace `mlr --csv sort ...` with `\mlr --csv sort ...`?

**Comment by indigoviolet** [comment]
```shell
❯ which mlr    
/home/linuxbrew/.linuxbrew/bin/mlr


❯ ls -l $(which mlr)   
lrwxrwxrwx 1 venky venky 30 Aug 10 10:39 /home/linuxbrew/.linuxbrew/bin/mlr -> ../Cellar/miller/6.3.0/bin/mlr


❯ echo 'mlr --csv sort -f subject,object P1056.csv' | od -a 
0000000   m   l   r  sp   -   -   c   s   v  sp   s   o   r   t  sp   -
0000020   f  sp   s   u   b   j   e   c   t   ,   o   b   j   e   c   t
0000040  sp   P   1   0   5   6   .   c   s   v  nl
0000053


❯ mlr --csv sort -f subject,object P1056.csv | od -a       
Usage: mlr sort {flags}

<snip>
0000000


❯ alias mlr                     


❯ mlr --version                                                                                                                                                             
mlr 6.3.0

❯ \mlr --version                                                                                                                                                            
mlr 6.3.0

❯ \mlr --csv sort -f subject,object P1056.csv              
Usage: mlr sort {flags}
<snip>
```

**Comment by indigoviolet** [comment]
Even weirder: I built from source to see if that was the problem:

```
❯ CC= make check      
go build github.com/johnkerl/miller/cmd/mlr
Build complete. The Miller executable is ./mlr (or .\mlr.exe on Windows).

<snip>

PASS overall
--- PASS: TestRegression (21.82s)
PASS
ok      command-line-arguments  21.823s
Tests complete. You can use 'make install' if you like, optionally preceded
by './configure --prefix=/your/install/path' if you wish to install to
somewhere other than /usr/local/bin -- the default prefix is /usr/local.


❯ ./mlr --csv sort -f subject,object ~/dev/instant-science/wikidata/P1056.csv            
Usage: mlr sort {flags}
<snip>

❯ ./mlr --version
mlr 6.3.0-dev

````

**Comment by johnkerl** [comment]
@indigoviolet what OS and what shell are you using?? 🤔

**Comment by johnkerl** [comment]
Also what other verbs besides `mlr cat` (OK) and `mlr sort` (not)? What about `mlr head` or `mlr tail` ?

**Comment by indigoviolet** [comment]
```
❯ lsb_release -a   
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute

❯ uname -a   
Linux venky-mxp 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

❯ $SHELL --version
zsh 5.8 (x86_64-ubuntu-linux-gnu)
```

`head`, `tail`, `cut`, `count`, `most-frequent` are all working.

**Comment by johnkerl** [comment]
@indigoviolet weird 😬

**Comment by johnkerl** [comment]
> Even weirder: I built from source to see if that was the problem:

OK, if we're building from source 😁 ... can you go here
https://github.com/johnkerl/miller/blob/main/internal/pkg/transformers/sort.go#L71
and put a line `panic("WHERE AM I")`, then build and re-run?

**Comment by indigoviolet** [comment]
```
❯ ./mlr --csv sort -f country ~/dev/instant-science/explore/test.csv
Usage: mlr sort {flags}
Sorts records primarily by the first specified field, secondarily by the second
field, and so on.  (Any records not having all specified sort keys will appear
at the end of the output, in the order they were encountered, regardless of the
panic: WHERE AM I

goroutine 1 [running]:
github.com/johnkerl/miller/internal/pkg/transformers.transformerSortUsage(0xc000010020)
        /home/venky/dev/miller/internal/pkg/transformers/sort.go:74 +0x18a
github.com/johnkerl/miller/internal/pkg/transformers.transformerSortParseCLI(0xc00002c7e8, 0x8, 0xc000020180, 0x8, 0x8, 0xc000097380, 0x0, 0x1, 0xc0000df9a8)
        /home/venky/dev/miller/internal/pkg/transformers/sort.go:260 +0x99a
github.com/johnkerl/miller/internal/pkg/climain.parseCommandLinePassOne(0xc000020180, 0x8, 0x8, 0xc000020180, 0x8, 0x8, 0x0, 0x0, 0xc0000ab800, 0x5, ...)
        /home/venky/dev/miller/internal/pkg/climain/mlrcli_parse.go:194 +0x4c7
github.com/johnkerl/miller/internal/pkg/climain.ParseCommandLine(0xc000020180, 0x8, 0x8, 0xc000020180, 0x8, 0x8, 0xe0, 0xc00009b680, 0xc0000dfd50)
        /home/venky/dev/miller/internal/pkg/climain/mlrcli_parse.go:102 +0xba
github.com/johnkerl/miller/internal/pkg/entrypoint.Main(0x1f4)
        /home/venky/dev/miller/internal/pkg/entrypoint/entrypoint.go:54 +0xcd
main.main()
        /home/venky/dev/miller/cmd/mlr/main.go:78 +0x14f
```

**Comment by indigoviolet** [comment]
Ok, I think I figured out what was happening:

For some forgotten reason I had aliased `sort` to `sort -S 75%`, which is ok, but in zsh you can have global aliases that are substituted anywhere on the command line, and I had `alias -g sort="sort -S 75%`. 

Unaliasing sort fixed the problem. Thank you for helping debug this!

**Comment by indigoviolet** [comment]
This was really close:

> What does echo 'mlr --csv sort -f subject ... | od -a show?

```shell
❯ echo ./mlr --csv sort -f subject,object ~/dev/instant-science/wikidata/P1056.csv            
./mlr --csv sort -S 75% -f subject,object /home/venky/dev/instant-science/wikidata/P1056.csv
```

**Comment by johnkerl** [comment]
Thanks @indigoviolet -- TIL about `zsh` aliases!! 😁
