### ISSUE TITLE
Weird error message with a wrong input file list

### ISSUE THREAD

**Issue by Poshi** [johnkerl/miller#1094]
I'v got an ugly error message when messing up the input files:
```
$ mlr --csv --mfrom analysis*csv cat > result.csv
panic: runtime error: index out of range [15] with length 15

goroutine 1 [running]:
github.com/johnkerl/miller/internal/pkg/cli.glob..func172({0xc0001ae000, 0x7ffdc4a182c8, 0x7}, 0xf, 0xc00002a700, 0xc0000f0820)
        github.com/johnkerl/miller/internal/pkg/cli/option_parse.go:2703 +0x1c8
github.com/johnkerl/miller/internal/pkg/cli.(*FlagTable).Parse(0x7ffdc4a182c8, {0xc0001ae000, 0xc00008b9a8, 0x10}, 0xc00008b9a8, 0xc00002a700, 0x7d0640)
        github.com/johnkerl/miller/internal/pkg/cli/flag_types.go:154 +0x1eb
github.com/johnkerl/miller/internal/pkg/climain.parseCommandLinePassOne({0xc0001ae000, 0xf, 0xc0001ae000})
        github.com/johnkerl/miller/internal/pkg/climain/mlrcli_parse.go:151 +0xa77
github.com/johnkerl/miller/internal/pkg/climain.ParseCommandLine({0xc0001ae000, 0xf, 0x10})
        github.com/johnkerl/miller/internal/pkg/climain/mlrcli_parse.go:99 +0x25
github.com/johnkerl/miller/internal/pkg/entrypoint.Main()
        github.com/johnkerl/miller/internal/pkg/entrypoint/entrypoint.go:50 +0x90
main.main()
        github.com/johnkerl/miller/cmd/mlr/main.go:78 +0x685
```

It has been solved by properly marking the end of the input file list:
`$ mlr --csv --mfrom analysis*csv -- cat > result.csv`
But the error message is terrifying and non-informative. There could be probably a better way to handle this :-)

For completeness, the file list expands to 11 files.

**Comment by johnkerl** [comment]
@Poshi https://github.com/johnkerl/miller/pull/1098

Wow, sorry, that was an embarrassing mistake for me to have made :(

**Comment by Poshi** [comment]
Don't worry, bugs are like accidents: nobody wants them, but they still happen. And the bigger the code, the more possibilities of something going wrong.
Good work!
