### ISSUE TITLE
${} doesn't work with accents

### ISSUE THREAD

**Issue by mikael-s** [johnkerl/miller#1407]
Hello,
I have TSV data in which fields names both have spaces and accents. When referring to one of this field in a `filter` command I'm protecting them with curly braces. However, while this works when a field name has spaces, it doesn't when it has accents.

Small examples:

`test1.tsv`:
```
Test pâté
25.8
28.6
31.6
31.3
23.9
```

`mlr --tsv filter '${Test pâté}>30' test1.tsv` fails with:

```
mlr: cannot parse DSL expression.
Parse error on token "${Test pâ" at line 1 column 1.
```

`test2.tsv`:
```
pâté
25.8
28.6
31.6
31.3
23.9
```

`mlr --tsv filter '${pâté}>30' test2.tsv` also fails but `mlr --tsv filter '$pâté>30' test2.tsv` succeeds

`test3.tsv`:
```
Test pate
25.8
28.6
31.6
31.3
23.9
```

`mlr --tsv filter '${Test pate}>30' /tmp/test3.tsv` also succeeds.

Thanks!

**Comment by johnkerl** [comment]
Hi @mikael-s !!

This looks like https://github.com/johnkerl/miller/pull/1363 which was included in https://github.com/johnkerl/miller/releases/tag/v6.9.0 -- can I ask you to share your `mlr --version` output please?

**Comment by mikael-s** [comment]
Indeed, it seems the same as #1363.
Sorry, I forgot to mention my version: 6.8.0 (installed through conda, which is the latest version available).

**Comment by aborruso** [comment]
I confirm that it works using 6.9

**Comment by johnkerl** [comment]
@mikael-s OK I need to ping the Conda folks ...

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/issues/1408

**Comment by mikael-s** [comment]
Thanks for the deployment of 6.9.0 in Conda!

Unfortunately, one of my case is still not working.

The `test1.tsv` is working seamlessly, as you shown:

```
$ mlr --tsv filter '${Test pâté}>30' test1.tsv
Test pâté
31.6
31.3
```

However the `test2.tsv` doesn't:

```
$ mlr --tsv filter '${pâté}>30' test2.tsv
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [select]:
github.com/johnkerl/miller/internal/pkg/stream.Stream({0xc000122890, 0x1, 0x1}, 0xc0001cc700, {0xc000116d80, 0x2, 0x2}, {0x9d7e48?, 0xc00005e030}, 0x1)
	/home/conda/feedstock_root/build_artifacts/miller_1697057214807/work/internal/pkg/stream/stream.go:95 +0x672
github.com/johnkerl/miller/internal/pkg/entrypoint.processToStdout(...)
	/home/conda/feedstock_root/build_artifacts/miller_1697057214807/work/internal/pkg/entrypoint/entrypoint.go:82
github.com/johnkerl/miller/internal/pkg/entrypoint.Main()
	/home/conda/feedstock_root/build_artifacts/miller_1697057214807/work/internal/pkg/entrypoint/entrypoint.go:61 +0x17b
main.main()
	/home/conda/feedstock_root/build_artifacts/miller_1697057214807/work/cmd/mlr/main.go:78 +0x5d8

goroutine 19 [chan receive]:
github.com/johnkerl/miller/internal/pkg/output.ChannelWriter(0x0?, {0x9d6920, 0xc000114420}, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/conda/feedstock_root/build_artifacts/miller_1697057214807/work/internal/pkg/output/channel_writer.go:24 +0x5a
created by github.com/johnkerl/miller/internal/pkg/stream.Stream in goroutine 1
	/home/conda/feedstock_root/build_artifacts/miller_1697057214807/work/internal/pkg/stream/stream.go:89 +0x5b1

goroutine 6 [chan receive]:
github.com/johnkerl/miller/internal/pkg/transformers.runSingleTransformer({0x9d5c20, 0xc000116d60}, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/conda/feedstock_root/build_artifacts/miller_1697057214807/work/internal/pkg/transformers/aaa_chain_transformer.go:211 +0x59
created by github.com/johnkerl/miller/internal/pkg/transformers.ChainTransformer in goroutine 18
	/home/conda/feedstock_root/build_artifacts/miller_1697057214807/work/internal/pkg/transformers/aaa_chain_transformer.go:187 +0x18a

goroutine 7 [chan receive]:
github.com/johnkerl/miller/internal/pkg/transformers.runSingleTransformer({0x9d56a0, 0xc0001da150}, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/conda/feedstock_root/build_artifacts/miller_1697057214807/work/internal/pkg/transformers/aaa_chain_transformer.go:211 +0x59
created by github.com/johnkerl/miller/internal/pkg/transformers.ChainTransformer in goroutine 18
	/home/conda/feedstock_root/build_artifacts/miller_1697057214807/work/internal/pkg/transformers/aaa_chain_transformer.go:187 +0x18a
```

**Comment by johnkerl** [comment]
Closing as resolved by https://github.com/johnkerl/miller/issues/1408 -- please let me know if this is in error and we can re-open -- thank you!
