### ISSUE TITLE
Segfault while parsing CLI Input

### ISSUE THREAD

**Issue by psacawa** [johnkerl/miller#828]
miller: **mlr 6.0.0-rc**
OS: **Ubuntu Linux 20.04.2 LTS**

When running  simple commands on the [`example.csv`](https://miller.readthedocs.io/en/latest/example.csv) from  the documentation, `mlr --csv tail -n 4 example.csv` works as expected, while `mlr --csv tail -n4 example.csv` generated a segfault:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x804a33]

goroutine 5 [running]:
container/list.(*List).Remove(...)
	/opt/hostedtoolcache/go/1.15.15/x64/src/container/list/list.go:138
github.com/johnkerl/miller/internal/pkg/transformers.(*TransformerTail).Transform(0xc0001956b0, 0xc0001803c0, 0xc000226960, 0xc0000380e0, 0xc00021e070)
	/home/runner/work/miller/miller/internal/pkg/transformers/tail.go:151 +0x553
github.com/johnkerl/miller/internal/pkg/transformers.runSingleTransformerBatch(0xc000195740, 0x9ad7e0, 0xc0001956b0, 0x1, 0xc00007e060, 0xc0000380e0, 0xc00021e070, 0xc0001991e0, 0x0)
	/home/runner/work/miller/miller/internal/pkg/transformers/aaa_chain_transformer.go:269 +0x1b2
github.com/johnkerl/miller/internal/pkg/transformers.runSingleTransformer(0x9ad7e0, 0xc0001956b0, 0x1, 0xc0001b2b40, 0xc00007e060, 0xc0000380e0, 0xc00021e070, 0xc0001991e0)
	/home/runner/work/miller/miller/internal/pkg/transformers/aaa_chain_transformer.go:212 +0xa5
created by github.com/johnkerl/miller/internal/pkg/transformers.ChainTransformer
	/home/runner/work/miller/miller/internal/pkg/transformers/aaa_chain_transformer.go:187 +0x28c
```

The corresponding segfault doesn't happen if you replace tail with head.

**Comment by johnkerl** [comment]
Thanks @psacawa !! `tail -n4` should not work, but, it should _definitely_ not segfault. :(

**Comment by johnkerl** [comment]
@all-contributors please add @psacawa for bug

**Comment by johnkerl** [comment]
@psacawa I believe #832 fixes this issue -- please let me know if I've missed anything -- thank you!!
