### ISSUE TITLE
mlr 6: "fatal error: runtime: out of memory" 

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#991]
Hi,
when I run the below command on [this file](https://github.com/johnkerl/miller/files/8308767/test.zip)

```
mlr --csv clean-whitespace then put '$datetime = strftime(strptime($DATA, "%d.%m.%Y"),"%Y-%m-%d")' then sort -f datetime,COGNOME,NOME test.csv >out.csv
```

I have the below error.

If I use miller 5 I have no error.

Am I doing something wrong?

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x905e02, 0x16)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc22c000000, 0x4000000, 0x23be438)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x23a2ee0, 0x400000, 0x7fffffffffff, 0xa468e8)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/malloc.go:727 +0x1e5
runtime.(*mheap).grow(0x23a2ee0, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/mheap.go:1344 +0x85
runtime.(*mheap).allocSpan(0x23a2ee0, 0x1, 0x7fab96c40500, 0x23be448, 0x7fab96c5edf0)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/mheap.go:1160 +0x6b6
runtime.(*mheap).alloc.func1()
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/mheap.go:907 +0x65
runtime.systemstack(0x7fabc0000020)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/proc.go:1116

goroutine 5 [running]:
runtime.systemstack_switch()
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/asm_amd64.s:330 fp=0xc0000f7768 sp=0xc0000f7760 pc=0x46f100
runtime.(*mheap).alloc(0x23a2ee0, 0x1, 0x7fab96fc0105, 0xc001500000)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/mheap.go:901 +0x85 fp=0xc0000f77b8 sp=0xc0000f7768 pc=0x429025
runtime.(*mcentral).grow(0x23b3898, 0x0)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/mcentral.go:506 +0x7a fp=0xc0000f7800 sp=0xc0000f77b8 pc=0x41a3ba
runtime.(*mcentral).cacheSpan(0x23b3898, 0x7fab96c5fb78)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/mcentral.go:177 +0x3e5 fp=0xc0000f7878 sp=0xc0000f7800 pc=0x41a145
runtime.(*mcache).refill(0x7fac0cd032f0, 0x205)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/mcache.go:142 +0xa5 fp=0xc0000f7898 sp=0xc0000f7878 pc=0x419ae5
runtime.(*mcache).nextFree(0x7fac0cd032f0, 0x5, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/malloc.go:880 +0x8d fp=0xc0000f78d0 sp=0xc0000f7898 pc=0x40ec0d
runtime.mallocgc(0x10, 0x0, 0xffffff00, 0xffffffffffffffff)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/malloc.go:1061 +0x834 fp=0xc0000f7970 sp=0xc0000f78d0 pc=0x40f5f4
runtime.growslice(0x87be80, 0xc22bfff150, 0x2, 0x2, 0x4, 0x20308a, 0x8a0240, 0xc00157e000)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/slice.go:224 +0x152 fp=0xc0000f79d8 sp=0xc0000f7970 pc=0x4503d2
regexp/syntax.appendRange(0xc22bfff150, 0x2, 0x2, 0xd0000000c, 0xc22bfff150, 0x2, 0x2)
        /opt/hostedtoolcache/go/1.15.15/x64/src/regexp/syntax/parse.go:1682 +0x114 fp=0xc0000f7a28 sp=0xc0000f79d8 pc=0x6928f4
regexp/syntax.appendClass(0xc22bfff150, 0x0, 0x2, 0xd3e760, 0x6, 0x6, 0x70, 0xc00009e9e8, 0xc22bfff110)
        /opt/hostedtoolcache/go/1.15.15/x64/src/regexp/syntax/parse.go:1731 +0x65 fp=0xc0000f7a78 sp=0xc0000f7a28 pc=0x692c65
regexp/syntax.(*parser).appendGroup(0xc22bfeb800, 0xc22bfff150, 0x0, 0x2, 0x1, 0xd3e760, 0x6, 0x6, 0x8e5f20, 0x1, ...)
        /opt/hostedtoolcache/go/1.15.15/x64/src/regexp/syntax/parse.go:1413 +0x105 fp=0xc0000f7ad0 sp=0xc0000f7a78 pc=0x691125
regexp/syntax.(*parser).parsePerlClassEscape(0xc22bfeb800, 0x8fc95d, 0x3, 0xc22bfff150, 0x0, 0x2, 0xc0000f7c68, 0x6a3233, 0xc22bfcdfb8, 0xc0001c400f, ...)
        /opt/hostedtoolcache/go/1.15.15/x64/src/regexp/syntax/parse.go:1384 +0x125 fp=0xc0000f7b38 sp=0xc0000f7ad0 pc=0x690cc5
regexp/syntax.Parse(0x8fc95d, 0x3, 0xd4, 0x8e2ce0, 0xc22bfcdff0, 0x4)
        /opt/hostedtoolcache/go/1.15.15/x64/src/regexp/syntax/parse.go:868 +0x605 fp=0xc0000f7c48 sp=0xc0000f7b38 pc=0x68e1c5
regexp.compile(0x8fc95d, 0x3, 0xd4, 0xc22bfcdf01, 0xc22bfff0a0, 0xc0000f7d58)
        /opt/hostedtoolcache/go/1.15.15/x64/src/regexp/regexp.go:170 +0x5a fp=0xc0000f7ce0 sp=0xc0000f7c48 pc=0x6a10fa
regexp.Compile(...)
        /opt/hostedtoolcache/go/1.15.15/x64/src/regexp/regexp.go:133
regexp.MustCompile(0x8fc95d, 0x3, 0xc22bfff030)
        /opt/hostedtoolcache/go/1.15.15/x64/src/regexp/regexp.go:309 +0x4b fp=0xc0000f7d68 sp=0xc0000f7ce0 pc=0x6a1eab
github.com/johnkerl/miller/internal/pkg/bifs.WhitespaceRegexp(...)
        /home/runner/work/miller/miller/internal/pkg/bifs/strings.go:197
github.com/johnkerl/miller/internal/pkg/bifs.BIF_clean_whitespace(0xc229d80690, 0xc22bfff0a0)
        /home/runner/work/miller/miller/internal/pkg/bifs/strings.go:242 +0x36 fp=0xc0000f7d90 sp=0xc0000f7d68 pc=0x708ad6
github.com/johnkerl/miller/internal/pkg/transformers.(*TransformerCleanWhitespace).cleanWhitespaceInKeysAndValues(0xc0000b6060, 0xc227c7e1e0, 0xc22b9f8f90, 0xc0000300e0, 0xc0001c0070)
        /home/runner/work/miller/miller/internal/pkg/transformers/clean_whitespace.go:160 +0xbb fp=0xc0000f7e10 sp=0xc0000f7d90 pc=0x7bc79b
github.com/johnkerl/miller/internal/pkg/transformers.(*TransformerCleanWhitespace).cleanWhitespaceInKeysAndValues-fm(0xc227c7e1e0, 0xc22b9f8f90, 0xc0000300e0, 0xc0001c0070)
        /home/runner/work/miller/miller/internal/pkg/transformers/clean_whitespace.go:147 +0x52 fp=0xc0000f7e48 sp=0xc0000f7e10 pc=0x81f272
github.com/johnkerl/miller/internal/pkg/transformers.(*TransformerCleanWhitespace).Transform(0xc0000b6060, 0xc227c7e1e0, 0xc22b9f8f90, 0xc0000300e0, 0xc0001c0070)
        /home/runner/work/miller/miller/internal/pkg/transformers/clean_whitespace.go:143 +0x69 fp=0xc0000f7e78 sp=0xc0000f7e48 pc=0x7bc6c9
github.com/johnkerl/miller/internal/pkg/transformers.runSingleTransformerBatch(0xc227c1d950, 0x9c0300, 0xc0000b6060, 0x1, 0xc000076060, 0xc0000300e0, 0xc0001c0070, 0xc00009f520, 0x0)
        /home/runner/work/miller/miller/internal/pkg/transformers/aaa_chain_transformer.go:269 +0x1b2 fp=0xc0000f7f40 sp=0xc0000f7e78 pc=0x7b5352
github.com/johnkerl/miller/internal/pkg/transformers.runSingleTransformer(0x9c0300, 0xc0000b6060, 0x1, 0xc0000b8ba0, 0xc000076060, 0xc0000300e0, 0xc0001c0070, 0xc00009f520)
        /home/runner/work/miller/miller/internal/pkg/transformers/aaa_chain_transformer.go:212 +0xa5 fp=0xc0000f7fa0 sp=0xc0000f7f40 pc=0x7b5165
runtime.goexit()
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000f7fa8 sp=0xc0000f7fa0 pc=0x470ee1
created by github.com/johnkerl/miller/internal/pkg/transformers.ChainTransformer
        /home/runner/work/miller/miller/internal/pkg/transformers/aaa_chain_transformer.go:187 +0x28c

goroutine 1 [select]:
github.com/johnkerl/miller/internal/pkg/stream.Stream(0xc0000991d0, 0x1, 0x1, 0xc00009f520, 0xc0000d84c0, 0x4, 0x4, 0x9c5580, 0xc0000b6008, 0xc0000d8401, ...)
        /home/runner/work/miller/miller/internal/pkg/stream/stream.go:94 +0x4ea
github.com/johnkerl/miller/internal/pkg/entrypoint.processToStdout(0xc00009f520, 0xc0000d84c0, 0x4, 0x4)
        /home/runner/work/miller/miller/internal/pkg/entrypoint/entrypoint.go:74 +0x9a
github.com/johnkerl/miller/internal/pkg/entrypoint.Main(0x1f4)
        /home/runner/work/miller/miller/internal/pkg/entrypoint/entrypoint.go:57 +0x255
main.main()
        /home/runner/work/miller/miller/cmd/mlr/main.go:78 +0x14f

goroutine 19 [chan send]:
github.com/johnkerl/miller/internal/pkg/input.(*RecordReaderCSV).processHandle(0xc0000caa50, 0x9c0ec0, 0xc0000b60d0, 0x7fff7826bc83, 0x8, 0xc00005cfa0, 0xc0000b8ba0, 0xc0000b8c60, 0xc0001c0070)
        /home/runner/work/miller/miller/internal/pkg/input/record_reader_csv.go:114 +0x33f
github.com/johnkerl/miller/internal/pkg/input.(*RecordReaderCSV).Read(0xc0000caa50, 0xc0000991d0, 0x1, 0x1, 0x7fff7826bc83, 0x8, 0x1, 0xe212f, 0xe212f, 0xc0000b8ba0, ...)
        /home/runner/work/miller/miller/internal/pkg/input/record_reader_csv.go:78 +0x23e
created by github.com/johnkerl/miller/internal/pkg/stream.Stream
        /home/runner/work/miller/miller/internal/pkg/stream/stream.go:86 +0x346

goroutine 21 [chan receive]:
github.com/johnkerl/miller/internal/pkg/output.ChannelWriter(0xc0000b8c00, 0x9c0100, 0xc00009bef0, 0xc00009f600, 0xc0001c0000, 0xc0000d8500, 0xc00009f501)
        /home/runner/work/miller/miller/internal/pkg/output/channel_writer.go:21 +0x45
created by github.com/johnkerl/miller/internal/pkg/stream.Stream
        /home/runner/work/miller/miller/internal/pkg/stream/stream.go:89 +0x42b

goroutine 6 [chan receive]:
github.com/johnkerl/miller/internal/pkg/transformers.runSingleTransformer(0x9c0620, 0xc0000a8e00, 0x0, 0xc000076060, 0xc0000760c0, 0xc000030150, 0xc0000300e0, 0xc00009f520)
        /home/runner/work/miller/miller/internal/pkg/transformers/aaa_chain_transformer.go:211 +0x45
created by github.com/johnkerl/miller/internal/pkg/transformers.ChainTransformer
        /home/runner/work/miller/miller/internal/pkg/transformers/aaa_chain_transformer.go:187 +0x28c

goroutine 7 [chan receive]:
github.com/johnkerl/miller/internal/pkg/transformers.runSingleTransformer(0x9c07c0, 0xc0000caa00, 0x0, 0xc0000760c0, 0xc000076120, 0xc0000301c0, 0xc000030150, 0xc00009f520)
        /home/runner/work/miller/miller/internal/pkg/transformers/aaa_chain_transformer.go:211 +0x45
created by github.com/johnkerl/miller/internal/pkg/transformers.ChainTransformer
        /home/runner/work/miller/miller/internal/pkg/transformers/aaa_chain_transformer.go:187 +0x28c

goroutine 8 [chan receive]:
github.com/johnkerl/miller/internal/pkg/transformers.runSingleTransformer(0x9c03e0, 0xc00009bec0, 0x0, 0xc000076120, 0xc0000b8c00, 0xc000030230, 0xc0000301c0, 0xc00009f520)
        /home/runner/work/miller/miller/internal/pkg/transformers/aaa_chain_transformer.go:211 +0x45
created by github.com/johnkerl/miller/internal/pkg/transformers.ChainTransformer
        /home/runner/work/miller/miller/internal/pkg/transformers/aaa_chain_transformer.go:187 +0x28c
```

**Comment by johnkerl** [comment]
@aborruso https://github.com/johnkerl/miller/pull/994 helps; still looking ...

**Comment by johnkerl** [comment]
@aborruso do you by any chance have `$GOGC` set to anything in your environment?

**Comment by aborruso** [comment]
> @aborruso do you by any chance have `$GOGC` set to anything in your environment?

If I run ` echo "$GOGC"` I have nothing

**Comment by johnkerl** [comment]
@aborruso can you send me the output of this?

```
GODEBUG=gctrace=1 mlr --csv --from test.csv \
  clean-whitespace \
  then put '$datetime = strftime(strptime($DATA, "%d.%m.%Y"),"%Y-%m-%d")' \
  then sort -f datetime,COGNOME,NOME \
  then tail -n 1
```

?

**Comment by johnkerl** [comment]
& please let me know if this is without or with https://github.com/johnkerl/miller/pull/994

**Comment by johnkerl** [comment]
For reference, I get (before & after -- with manually added left-alignment)

Before:

```
gc 1  @0.035s  13%: 0.020+15+0.052   ms clock, 0.081+12/14/14+0.21        ms cpu, 20->21->12       MB, 21   MB goal, 4 P
gc 2  @0.140s  11%: 0.050+65+0.023   ms clock, 0.20+3.4/61/45+0.092       ms cpu, 49->64->38       MB, 74   MB goal, 4 P
gc 3  @0.508s  9%:  0.35+164+0.048   ms clock, 1.4+4.2/145/88+0.19        ms cpu, 174->206->115    MB, 233  MB goal, 4 P
gc 4  @1.978s  4%:  0.26+159+0.047   ms clock, 1.0+7.5/158/276+0.19       ms cpu, 567->581->147    MB, 694  MB goal, 4 P
gc 5  @4.511s  4%:  0.036+328+0.038  ms clock, 0.14+104/320/603+0.15      ms cpu, 797->815->211    MB, 886  MB goal, 4 P
gc 6  @9.138s  6%:  0.63+1137+0.002  ms clock, 2.5+657/1136/1918+0.010    ms cpu, 1190->1273->362  MB, 1268 MB goal, 4 P
gc 7  @15.258s 6%:  0.84+1479+0.003  ms clock, 3.3+334/1478/2517+0.012    ms cpu, 2017->2160->572  MB, 2177 MB goal, 4 P
gc 8  @24.576s 8%:  1.1+3459+0.002   ms clock, 4.7+1821/3458/5619+0.010   ms cpu, 3191->3434->915  MB, 3433 MB goal, 4 P
gc 9  @43.400s 9%:  0.62+6041+0.021  ms clock, 2.4+3113/6032/9989+0.085   ms cpu, 5054->5478->1468 MB, 5495 MB goal, 4 P
gc 10 @67.478s 15%: 4.5+19744+0.003  ms clock, 18+15860/19737/32511+0.014 ms cpu, 8030->8793->2408 MB, 8812 MB goal, 4 P
```

After:

```
gc 1  @0.080s  25%: 0.013+47+0.002   ms clock, 0.055+81/47/47+0.010       ms cpu, 20->22->14       MB, 21   MB goal, 4 P
gc 2  @0.188s  18%: 0.045+40+0.029   ms clock, 0.18+3.6/40/21+0.11        ms cpu, 57->73->52       MB, 86   MB goal, 4 P
gc 3  @0.498s  11%: 0.025+86+0.040   ms clock, 0.10+1.6/86/134+0.16       ms cpu, 236->260->143    MB, 316  MB goal, 4 P
gc 4  @1.624s  7%:  0.030+278+0.016  ms clock, 0.12+2.0/277/398+0.064     ms cpu, 727->801->324    MB, 863  MB goal, 4 P
gc 5  @4.367s  6%:  0.033+693+0.014  ms clock, 0.13+1.6/693/1004+0.058    ms cpu, 1722->1909->750  MB, 1945 MB goal, 4 P
gc 6  @12.178s 14%: 0.052+5593+0.003 ms clock, 0.21+3644/5593/7047+0.014  ms cpu, 4063->4517->1768 MB, 4503 MB goal, 4 P
```

**Comment by aborruso** [comment]
> @aborruso can you send me the output of this?

I have

```
gc 1 @0.038s 3%: 0.081+5.4+0.037 ms clock, 0.65+5.0/6.9/8.9+0.29 ms cpu, 20->21->6 MB, 21 MB goal, 8 P
gc 2 @0.073s 4%: 0.55+4.2+0.070 ms clock, 4.4+2.6/8.0/15+0.56 ms cpu, 27->28->9 MB, 41 MB goal, 8 P
gc 3 @0.132s 3%: 0.076+6.9+0.058 ms clock, 0.61+2.2/12/24+0.46 ms cpu, 48->50->16 MB, 59 MB goal, 8 P
gc 4 @0.235s 3%: 0.026+12+0.036 ms clock, 0.20+2.2/22/39+0.29 ms cpu, 89->94->30 MB, 99 MB goal, 8 P
gc 5 @0.496s 2%: 0.13+21+0.070 ms clock, 1.0+6.4/42/71+0.56 ms cpu, 169->174->54 MB, 182 MB goal, 8 P
gc 6 @0.910s 2%: 0.033+40+0.045 ms clock, 0.26+3.0/75/136+0.36 ms cpu, 309->320->99 MB, 326 MB goal, 8 P
gc 7 @1.729s 2%: 0.58+62+0.049 ms clock, 4.7+4.7/123/274+0.39 ms cpu, 572->587->182 MB, 597 MB goal, 8 P
gc 8 @3.303s 2%: 0.043+122+0.047 ms clock, 0.34+2.2/241/543+0.38 ms cpu, 1050->1075->269 MB, 1095 MB goal, 8 P
gc 9 @6.607s 2%: 0.057+279+0.054 ms clock, 0.45+1.6/555/1251+0.43 ms cpu, 1550->1589->399 MB, 1617 MB goal, 8 P
gc 10 @12.339s 2%: 1.3+952+0.065 ms clock, 11+118/1903/4397+0.52 ms cpu, 2296->2408->637 MB, 2396 MB goal, 8 P
gc 11 @21.133s 3%: 0.30+1085+0.081 ms clock, 2.4+3.6/2165/4988+0.65 ms cpu, 3667->3752->882 MB, 3827 MB goal, 8 P
gc 12 @32.204s 2%: 13+1204+0.057 ms clock, 104+36/2399/5375+0.46 ms cpu, 5075->5223->1314 MB, 5296 MB goal, 8 P
gc 13 @60.485s 14%: 43+31415+0.008 ms clock, 344+37160/62808/145917+0.064 ms cpu, 7556->7967->2127 MB, 7885 MB goal, 8 P
```

**Comment by aborruso** [comment]
> & please let me know if this is without or with #994

I have no error, it works :)
